# Generated by Django 4.1.3 on 2022-12-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="userId",),
        migrations.AlterField(
            model_name="member",
            name="hobby",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
