# Generated by Django 4.1.3 on 2023-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("passwd", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("hobby", models.CharField(blank=True, max_length=50, null=True)),
                ("job", models.CharField(max_length=50)),
                ("reg_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
